apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"k6-operator-leader-election-rolebinding","namespace":"k6-operator-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"k6-operator-leader-election-role"},"subjects":[{"kind":"ServiceAccount","name":"k6-operator","namespace":"k6-operator-system"}]}
  creationTimestamp: "2021-06-29T11:00:04Z"
  managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:roleRef:
          f:apiGroup: {}
          f:kind: {}
          f:name: {}
        f:subjects: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2021-06-29T11:00:04Z"
  name: k6-operator-leader-election-rolebinding
  namespace: k6-operator-system
  resourceVersion: "471"
  uid: 5fd30b3b-59ac-4f4b-8224-1aef00f757e5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k6-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: k6-operator
    namespace: k6-operator-system
